default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: postgres
  username: postgres
  password: postgres


development:
  <<: *default
  database: week1_4_development


test:
  <<: *default
  database: week1_4_test
